name: Build PDF from LaTeX

on:
  push:
    paths:
      - '**.tex'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: appendix.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: compiled-pdf
          path: appendix.pdf
          
      - uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: main.pdf

          
